name: Build & Test backend

on:
  pull_request:
    branches-ignore:
      - release
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Node.js (via NVM)
        working-directory: ./backend
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          . "$NVM_DIR/nvm.sh"
          nvm install
          nvm use

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('backend/package.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install Dependencies
        working-directory: ./backend
        run: yarn install --frozen-lockfile

      - name: Build Backend
        working-directory: ./backend
        run: yarn build

      - name: Run Backend Tests
        working-directory: ./backend
        run: yarn test

